<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="SAMINCHANA" name="SecondMavenProject.SecondMavenProject.DependsOnMethod" tests="9" failures="1" timestamp="2019-11-28T10:53:25 IST" time="0.028" errors="0">
  <testcase name="test4" time="0.002" classname="SecondMavenProject.SecondMavenProject.DependsOnMethod"/>
  <testcase name="test6" time="0.002" classname="SecondMavenProject.SecondMavenProject.DependsOnMethod"/>
  <testcase name="test1" time="0.012" classname="SecondMavenProject.SecondMavenProject.DependsOnMethod"/>
  <testcase name="test2" time="0.002" classname="SecondMavenProject.SecondMavenProject.DependsOnMethod">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at SecondMavenProject.SecondMavenProject.DependsOnMethod.test2(DependsOnMethod.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="SecondMavenProject.SecondMavenProject.DependsOnMethod">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="SecondMavenProject.SecondMavenProject.DependsOnMethod">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.004" classname="SecondMavenProject.SecondMavenProject.DependsOnMethod">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.000" classname="SecondMavenProject.SecondMavenProject.DependsOnMethod">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test5" time="0.002" classname="SecondMavenProject.SecondMavenProject.DependsOnMethod"/>
</testsuite> <!-- SecondMavenProject.SecondMavenProject.DependsOnMethod -->
